void readEeprom();
void scanWifi();
void writeEeprom();

void readEepromAddress();
void refreshData();
void ledBlink(byte n, int t);
void kontr_temp();
void analoReadA0(); 
void defineDevice();
void readEEPROMTimerToObjeckt();
void readSensorsAddressTemp();
void writeStringEeprom(word beginByteEeprom, word maxLengthString, String str, word symbol);
void readEepromNameRele();
void manual_vklOtkl(int onOff, int numRele);
void searchCodeSennsorInEEPROM();
void sendSensorData();
void refreshobjectToJsonDate();
void getDateTime();
void controlPins();
byte controlRangeHour( byte numberRele, byte numberDataTime); 
boolean controlRangeDate(byte numberRele, byte numberDataTime);
String EEPROMDataToJSONSensor();
String EEPROMDataToJSONOnOff();
String ds18b20EEpromToJSONnameSensor();

 int controlPin(byte numberRele, int counterPin, byte pinConected);
void prin(String s, byte a); 
void prin(String s, word a); 
void prin(String s, int a); 
void prin(String s, double a); 
void prin(String s, float a); 
void prin(String s, char a); 
void prin(String s, String a); 
void prinString(String s);
void prin(String s);
void prinEEPROMDebag(int starting, int lengthSection, String nameSection);
int parseStringToData(String stringData);
unsigned long nextElement(String s);
String readStringEeprom(int beginByteEeprom, int lengthString );
void writeStringEeprom(word beginByteEeprom, word maxLengthString, String str, word symbol );
